### PR TITLE
[SRM-658] Test jwt patch to fix `strpos` deprication for PHP 8.x

### PR DESCRIPTION
**Pull request by mayurngondhkar**
**JIRA** https://digital-vic.atlassian.net/browse/SRM-658

Changes

1. Test https://www.drupal.org/project/jwt/issues/3298726 patches

### CODE REVIEW

**Comment by vincent-gao** [comment]
are we still using jwt module? @mayurngondhkar

**Comment by mayurngondhkar** [comment]
> are we still using jwt module? @mayurngondhkar

Not sure. But it was throwing an error. Its still listed in the composer.json. Where can I check? @vincent-gao

**Comment by anthony-malkoun** [comment]
> > are we still using jwt module? @mayurngondhkar
> 
> Not sure. But it was throwing an error. Its still listed in the composer.json. Where can I check? @vincent-gao

I think `tide_authenticated_content` requires it for login/register.

image

**Review by anthony-malkoun — APPROVED** [review]
👍

**Comment by mayurngondhkar** [comment]
Ignore [1cfa6c1](https://github.com/dpc-sdp/tide_authenticated_content/commit/1cfa6c124c7c7eed240172b858ddf0807d7efe8c)

**Pull request merged**
